//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolunProject.Data.EntityADO.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public string PostID { get; set; }
        public string VolunteerID { get; set; }
        public string Caption { get; set; }
        public System.DateTime CreateDate { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> PostLike { get; set; }
        public Nullable<bool> State { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Volunteer Volunteer { get; set; }
    }
}
